#!/usr/bin/env bash
curl -o $LIVECHECKER_FILE -L https://gist.github.com/SeekerTestBot/$LIVECHECKER_GIST/raw
brew ruby print-formulae.rb $LIVECHECKER_FILE > $HOME/.brew_livecheck_watchlist
if [ $? -eq 0 ]; then
  if [ ! -z "$LIVECHECKER_TAP" ]; then
    brew tap $LIVECHECKER_TAP
  fi
  brew ${LIVECHECKER_COMMAND:-livecheck} --newer-only --quiet > $LIVECHECKER_FILE || true
fi
cat $LIVECHECKER_FILE
exit 0
