#!/usr/bin/env bash
# Usage: ./update languages.txt
curl -o $1 -L $LIVECHECKER_GIST_URL/raw
brew ruby print-formulae.rb $1 > $HOME/.brew_livecheck_watchlist
if [ $? -eq 0 ]; then
  if [ ! -z "$LIVECHECKER_TAP" ]; then
    brew tap $LIVECHECKER_TAP
  fi
  brew ${LIVECHECKER_COMMAND:-livecheck} --newer-only --quiet > $1 || true
fi
cat $1
echo >> $1
exit 0
