name: Run livecheck

on:
  workflow_dispatch:
    inputs:
      skip_core:
        default: false
      skip_cask:
        default: false
      skip_linux:
        default: false
      skip_bio:
        default: false
      skip_languages:
        default: false

  schedule:
    - cron: '0 4 * * *'

env:
  HOMEBREW_NO_COLOR: 1
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:

  core:
    if: ${{ !github.event.inputs.skip_core }}
    runs-on: macos-latest
    steps:
      - run: brew update-reset
      - run: brew livecheck --newer-only --quiet --tap homebrew/core > core.txt || true
      - run: cat core.txt
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: https://gist.github.com/SeekerTestBot/26cd541935bd0380a0ac0e996fc56195
          gist_file_name: homebrew-core.txt
          file_path: core.txt

  cask:
    if: ${{ !github.event.inputs.skip_cask }}
    runs-on: macos-latest
    steps:
      - run: brew update-reset
      - run: brew tap SeekingMeaning/cask-livecheck
      - run: brew cask-livecheck --newer-only --quiet --tap homebrew/cask > cask.txt || true
      - run: cat cask.txt
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: https://gist.github.com/SeekerTestBot/94b2ada768a1b2c5839667414806d2b0
          gist_file_name: homebrew-cask.txt
          file_path: cask.txt

  linux:
    if: ${{ !github.event.inputs.skip_linux }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: brew ruby $GITHUB_WORKSPACE/print-linux.rb > $HOME/.brew_livecheck_watchlist
      - run: brew livecheck --newer-only --quiet > linux.txt || true
      - run: cat linux.txt
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: https://gist.github.com/SeekerTestBot/58843cb8fdd4b3a6ef841b066726209a
          gist_file_name: linuxbrew-core.txt
          file_path: linux.txt

  bio:
    if: ${{ !github.event.inputs.skip_bio }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - run: brew update-reset
      - run: brew tap brewsci/bio
      - run: brew livecheck --newer-only --quiet --tap brewsci/bio > bio.txt || true
      - run: cat bio.txt
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: https://gist.github.com/SeekerTestBot/d804d3e7a2895257d47c26abf9ae486a
          gist_file_name: brewsci-bio.txt
          file_path: bio.txt

  languages:
    if: ${{ !github.event.inputs.skip_languages }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - run: brew update-reset
      - run: brew tap SeekingMeaning/languages
      - run: brew livecheck --newer-only --quiet --tap SeekingMeaning/languages > languages.txt || true
      - run: cat languages.txt
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: https://gist.github.com/SeekerTestBot/6f87957bdeecb59238ffd770e3d36431
          gist_file_name: seekingmeaning-languages.txt
          file_path: languages.txt
