name: Run livecheck

on:
  workflow_dispatch:
    inputs:
      skip_core:
        default: false
      skip_cask:
        default: false
      skip_linux:
        default: false
      skip_bio:
        default: false

#   schedule:
#     - cron: '0 4 * * *'

env:
  HOMEBREW_NO_COLOR: 1
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:

  core:
    if: ${{ !github.event.inputs.skip_core }}
    runs-on: macos-latest
    env:
      LIVECHECKER_TAP: homebrew/core
      LIVECHECKER_FILE: homebrew-core.txt
      LIVECHECKER_GIST: 26cd541935bd0380a0ac0e996fc56195
    steps:
      - run: brew update-reset
      - run: brew livecheck --formulae --newer-only --quiet --tap $LIVECHECKER_TAP > $LIVECHECKER_FILE || true
      - run: cat $LIVECHECKER_FILE
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ env.LIVECHECKER_GIST }}
          gist_file_name: ${{ env.LIVECHECKER_FILE }}
          file_path: ${{ env.LIVECHECKER_FILE }}

  cask:
    if: ${{ !github.event.inputs.skip_cask }}
    runs-on: macos-latest
    env:
      LIVECHECKER_TAP: homebrew/cask
      LIVECHECKER_FILE: homebrew-cask.txt
      LIVECHECKER_GIST: 94b2ada768a1b2c5839667414806d2b0
    steps:
      - run: brew update-reset
      - run: brew install-bundler-gems
      - run: brew livecheck --casks --newer-only --quiet --tap $LIVECHECKER_TAP > $LIVECHECKER_FILE || true
      - run: cat $LIVECHECKER_FILE
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ env.LIVECHECKER_GIST }}
          gist_file_name: ${{ env.LIVECHECKER_FILE }}
          file_path: ${{ env.LIVECHECKER_FILE }}

  linux:
    if: ${{ !github.event.inputs.skip_linux }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_TAP: homebrew/core
      LIVECHECKER_FILE: linuxbrew-core.txt
      LIVECHECKER_GIST: 58843cb8fdd4b3a6ef841b066726209a
    steps:
      - uses: actions/checkout@v2
      - run: brew update-reset
      - run: brew ruby $GITHUB_WORKSPACE/print-linux.rb $LIVECHECKER_TAP > $HOME/.brew_livecheck_watchlist
      - run: brew livecheck --formulae --newer-only --quiet > $LIVECHECKER_FILE || true
      - run: cat $LIVECHECKER_FILE
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ env.LIVECHECKER_GIST }}
          gist_file_name: ${{ env.LIVECHECKER_FILE }}
          file_path: ${{ env.LIVECHECKER_FILE }}

  bio:
    if: ${{ !github.event.inputs.skip_bio }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_TAP: brewsci/bio
      LIVECHECKER_FILE: brewsci-bio.txt
      LIVECHECKER_GIST: d804d3e7a2895257d47c26abf9ae486a
    steps:
      - run: brew update-reset
      - run: brew tap $LIVECHECKER_TAP
      - run: brew livecheck --formulae --newer-only --quiet --tap $LIVECHECKER_TAP > $LIVECHECKER_FILE || true
      - run: cat $LIVECHECKER_FILE
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ env.LIVECHECKER_GIST }}
          gist_file_name: ${{ env.LIVECHECKER_FILE }}
          file_path: ${{ env.LIVECHECKER_FILE }}
