name: Update gists

on:
  workflow_dispatch:
    inputs:
      skip_core:
        default: false
      skip_cask:
        default: false
      skip_linux:
        default: false
      skip_bio:
        default: false
      skip_languages:
        default: false

  schedule:
    - cron: '0 10,16,22 * * *'

env:
  HOMEBREW_NO_COLOR: 1
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:

  core:
    if: ${{ !github.event.inputs.skip_core }}
    runs-on: macos-latest
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/26cd541935bd0380a0ac0e996fc56195
      LIVECHECKER_FILE: homebrew-core.txt
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: ${{ env.LIVECHECKER_FILE }}
  gist-core:
    needs: core
    runs-on: ubuntu-latest
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/26cd541935bd0380a0ac0e996fc56195
      LIVECHECKER_FILE: homebrew-core.txt
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: core
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ env.LIVECHECKER_GIST }}
          gist_title: ${{ env.LIVECHECKER_FILE }}
          github_file: ${{ env.LIVECHECKER_FILE }}

  cask:
    if: ${{ !github.event.inputs.skip_cask }}
    runs-on: macos-latest
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/94b2ada768a1b2c5839667414806d2b0
      LIVECHECKER_FILE: homebrew-cask.txt
      LIVECHECKER_TAP: SeekingMeaning/cask-livecheck
      LIVECHECKER_COMMAND: cask-livecheck
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: ${{ env.LIVECHECKER_FILE }}
  gist-cask:
    needs: cask
    runs-on: ubuntu-latest
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/58843cb8fdd4b3a6ef841b066726209a
      LIVECHECKER_FILE: linuxbrew-core.txt
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cask
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ env.LIVECHECKER_GIST }}
          gist_title: ${{ env.LIVECHECKER_FILE }}
          github_file: ${{ env.LIVECHECKER_FILE }}

  linux:
    if: ${{ !github.event.inputs.skip_linux }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/58843cb8fdd4b3a6ef841b066726209a
      LIVECHECKER_FILE: linuxbrew-core.txt
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: ${{ env.LIVECHECKER_FILE }}
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ env.LIVECHECKER_GIST }}
          gist_title: ${{ env.LIVECHECKER_FILE }}
          github_file: ${{ env.LIVECHECKER_FILE }}

  bio:
    if: ${{ !github.event.inputs.skip_bio }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/d804d3e7a2895257d47c26abf9ae486a
      LIVECHECKER_FILE: brewsci-bio.txt
      LIVECHECKER_TAP: brewsci/bio
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: ${{ env.LIVECHECKER_FILE }}
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ env.LIVECHECKER_GIST }}
          gist_title: ${{ env.LIVECHECKER_FILE }}
          github_file: ${{ env.LIVECHECKER_FILE }}

  languages:
    if: ${{ !github.event.inputs.skip_languages }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/6f87957bdeecb59238ffd770e3d36431
      LIVECHECKER_FILE: seekingmeaning-languages.txt
      LIVECHECKER_TAP: SeekingMeaning/languages
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: ${{ env.LIVECHECKER_FILE }}
      - uses: exuanbo/actions-deploy-gist@v1.0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 6f87957bdeecb59238ffd770e3d36431
          gist_file_name: ${{ env.LIVECHECKER_FILE }}
          file_path: ${{ env.LIVECHECKER_FILE }}
