name: Update gists

on:
  workflow_dispatch:
    inputs:
      skip_core:
        default: false
      skip_cask:
        default: false
      skip_linux:
        default: false
      skip_bio:
        default: false
      skip_languages:
        default: false

  schedule:
    - cron: '0 10,16,22 * * *'

env:
  HOMEBREW_NO_COLOR: 1
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:

  check-core:
    if: ${{ !github.event.inputs.skip_core }}
    runs-on: macos-latest
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/26cd541935bd0380a0ac0e996fc56195
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update core.txt
      - uses: actions/upload-artifact@v2
        with:
          name: core
          path: core.txt

  check-cask:
    if: ${{ !github.event.inputs.skip_cask }}
    runs-on: macos-latest
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/94b2ada768a1b2c5839667414806d2b0
      LIVECHECKER_TAP: SeekingMeaning/cask-livecheck
      LIVECHECKER_COMMAND: cask-livecheck
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update cask.txt
      - uses: actions/upload-artifact@v2
        with:
          name: cask
          path: cask.txt

  check-linux:
    if: ${{ !github.event.inputs.skip_linux }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/58843cb8fdd4b3a6ef841b066726209a
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update linux.txt
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: linux.txt

  check-bio:
    if: ${{ !github.event.inputs.skip_bio }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/d804d3e7a2895257d47c26abf9ae486a
      LIVECHECKER_TAP: brewsci/bio
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update bio.txt
      - uses: actions/upload-artifact@v2
        with:
          name: bio
          path: bio.txt

  languages:
    if: ${{ !github.event.inputs.skip_languages }}
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      LIVECHECKER_GIST: https://gist.github.com/SeekerTestBot/6f87957bdeecb59238ffd770e3d36431
      LIVECHECKER_FILE: seekingmeaning-languages.txt
      LIVECHECKER_TAP: SeekingMeaning/languages
    steps:
      - run: brew update-reset
      - uses: actions/checkout@v2
      - run: ./update $LIVECHECKER_FILE
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: ${{ env.LIVECHECKER_FILE }}
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ env.LIVECHECKER_GIST }}
          gist_title: ${{ env.LIVECHECKER_FILE }}
          github_file: ${{ env.LIVECHECKER_FILE }}

  gist-core:
    needs: check-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: core
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/SeekerTestBot/26cd541935bd0380a0ac0e996fc56195
          gist_title: homebrew-core.txt
          github_file: core.txt

  gist-cask:
    needs: check-cask
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cask
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/SeekerTestBot/94b2ada768a1b2c5839667414806d2b0
          gist_title: homebrew-cask.txt
          github_file: cask.txt

  gist-linux:
    needs: check-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/SeekerTestBot/58843cb8fdd4b3a6ef841b066726209a
          gist_title: linuxbrew-core.txt
          github_file: linux.txt

  gist-bio:
    needs: check-bio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bio
      - uses: popsiclestick/gist-sync-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/SeekerTestBot/d804d3e7a2895257d47c26abf9ae486a
          gist_title: brewsci-bio.txt
          github_file: bio.txt

